// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-appkit — see LICENSE.

#pragma once

#include <juce_gui_basics/juce_gui_basics.h>

#include <felitronics/appkit/DeviceGlyphPaths.h>   // the geometry, generated from the same source as assets/glyphs/*.svg
#include <felitronics/appkit/DeviceSpec.h>         // DeviceType / DeviceSpec / parse (pure juce_core — the data model, unit-tested)
#include <felitronics/appkit/Flicker.h>            // the shared one-pole heater shimmer (also used by OrbitCab's TubeDisplay)

#include <string_view>
#include <utility>
#include <vector>

//==============================================================================
// felitronics::appkit — schematic glyphs for a preamp's active device: a triode (tube), a bipolar
// transistor (bjt), a FET, an analogue op-amp (ic), a digital chip (dsp), a diode, a transformer or
// a tape reel. Driven by the "device" spec (see DeviceSpec.h) so the UI shows WHAT a capture is —
// e.g. a tube for a Volt, a BJT for the transistor ISA, or a tube+BJT for a hybrid. Moved from
// OrbitCab ui/DeviceGlyph.h when the device visuals were promoted here.
//
// The drawings are not code any more: they are the path data in DeviceGlyphPaths.h, generated by
// tools/gen-glyphs.mjs together with assets/glyphs/<key>.svg, which is what the website draws. One
// geometry, two readers. The glow and the heater flicker (Flicker.h) stay code, on top of it.
//==============================================================================
namespace felitronics::appkit
{

namespace detail
{
    // The catalogue parsed once: one juce::Path per catalogue path, in the frame's own units.
    // Parsed on first use and kept for the process — the strings are constants, and a strip repaints
    // at 30 Hz. The initialisation is a function-local static (thread-safe) and nothing writes to it
    // afterwards, so whichever thread paints may call this.
    inline const std::vector<juce::Path>& glyphGeometry (std::string_view key)
    {
        static const auto parsed = []
        {
            std::vector<std::pair<std::string_view, std::vector<juce::Path>>> out;
            for (const auto& gl : glyphpaths::all)
            {
                std::vector<juce::Path> paths;
                for (const auto d : gl.paths)
                    paths.push_back (juce::Drawable::parseSVGPath (juce::String (d.data(), d.size())));
                out.emplace_back (gl.key, std::move (paths));
            }
            return out;
        }();

        for (const auto& entry : parsed)
            if (entry.first == key)
                return entry.second;

        static const std::vector<juce::Path> none;
        return none;
    }
}

// Draw the catalogue glyph named `key` (see DeviceGlyphPaths.h / assets/glyphs/) inside `r`, stroked
// in `c`. The 100 x 100 frame maps onto the square of side min(w, h) centred in `r`; the stroke is
// max(1 px, 0.11 R) with R half that side, round caps and joins, each catalogue path stroked on its
// own. Leads reach up to 8 % past the square and the round caps half a stroke beyond that, so callers
// pass a cell already inset by at least 12 % of its side on every edge, as the rows below do (8 % lets the caps
// out by about 1 % of the cell).
// An unknown key draws nothing.
inline void drawGlyph (juce::Graphics& g, juce::Rectangle<float> r, std::string_view key, juce::Colour c)
{
    const auto& paths = detail::glyphGeometry (key);
    if (paths.empty())
        return;

    const float R   = juce::jmin (r.getWidth(), r.getHeight()) * 0.5f;
    const auto  ctr = r.getCentre();
    const float sw  = juce::jmax (1.0f, R * 0.11f);   // stroke width, in pixels
    const auto  toCell = juce::AffineTransform::scale (R / 50.0f).translated (ctr.x - R, ctr.y - R);
    const juce::PathStrokeType stroke (sw, juce::PathStrokeType::curved, juce::PathStrokeType::rounded);

    g.setColour (c);
    for (const auto& p : paths)
    {
        auto placed = p;
        placed.applyTransform (toCell);
        g.strokePath (placed, stroke);
    }
}

// The catalogue key a device type draws: its SVG's file name under assets/glyphs/. Empty for none.
inline std::string_view deviceGlyphKey (DeviceType t)
{
    switch (t)
    {
        case DeviceType::tube:        return "tube";
        case DeviceType::bjt:         return "bjt";
        case DeviceType::fet:         return "fet";
        case DeviceType::ic:          return "ic";
        case DeviceType::dsp:         return "dsp";
        case DeviceType::diode:       return "diode";
        case DeviceType::transformer: return "transformer";
        case DeviceType::tape:        return "tape";
        case DeviceType::none:        break;
    }
    return {};
}

// One device symbol inside `r` (a square-ish cell), stroked in `c`. Kept schematic-simple so it
// reads at ~16 px: a triode (tube), a PNP transistor (bjt), a JFET (fet), an op-amp triangle (ic), a
// chip package (dsp), a diode, a transformer (two windings around a core), or a tape reel.
inline void drawDeviceGlyph (juce::Graphics& g, juce::Rectangle<float> r, DeviceType type, juce::Colour c)
{
    drawGlyph (g, r, deviceGlyphKey (type), c);
}

//==============================================================================
// The transfer-shape marks — a curve in a small plot frame, one per waveshaper shape. They are NOT
// devices: nothing in a capture's "device" spec names them, so they live outside DeviceType and
// DeviceSpec. A consumer names one by the enum (drawShapeGlyph (g, r, ShapeGlyph::atan, c)) or by its
// catalogue key ("shape-atan", the same name as the SVG file) through drawGlyph.
enum class ShapeGlyph { tanh, atan, cubic, asym };

inline std::string_view shapeGlyphKey (ShapeGlyph s)
{
    switch (s)
    {
        case ShapeGlyph::tanh:  return "shape-tanh";
        case ShapeGlyph::atan:  return "shape-atan";
        case ShapeGlyph::cubic: return "shape-cubic";
        case ShapeGlyph::asym:  return "shape-asym";
    }
    return {};
}

inline void drawShapeGlyph (juce::Graphics& g, juce::Rectangle<float> r, ShapeGlyph s, juce::Colour c)
{
    drawGlyph (g, r, shapeGlyphKey (s), c);
}

// Per-family colours: the glyph stroke and the (behind-glyph) glow. Warm=tube, blue=BJT, green=FET.
inline juce::Colour deviceStroke (DeviceType t)
{
    switch (t) { case DeviceType::tube: return juce::Colour (0xfff2c793);
                 case DeviceType::bjt:  return juce::Colour (0xffc3dbf6);
                 case DeviceType::fet:  return juce::Colour (0xffc3edcf);
                 case DeviceType::dsp:  return juce::Colour (0xfff2b8b4);
                 case DeviceType::ic:   return juce::Colour (0xfff2b8e0);
                 case DeviceType::diode: return juce::Colour (0xffeef0f4);
                 case DeviceType::transformer: return juce::Colour (0xffbdeee9);
                 case DeviceType::tape: return juce::Colour (0xffdcccff);
                 case DeviceType::none: default: break; }   // explicit: keeps -Wswitch-enum consumers clean
    return juce::Colour (0xffb8b0a0);
}
inline juce::Colour deviceGlow (DeviceType t)
{
    switch (t) { case DeviceType::tube: return juce::Colour (0xffff9a3c);   // warm amber
                 case DeviceType::bjt:  return juce::Colour (0xff4e9ae8);   // blue (BJT)
                 case DeviceType::fet:  return juce::Colour (0xff58c877);   // green (FET)
                 case DeviceType::dsp:  return juce::Colour (0xffe23b3b);   // red (digital chip)
                 case DeviceType::ic:   return juce::Colour (0xffe264b4);   // magenta (analogue op-amp)
                 case DeviceType::diode: return juce::Colour (0xffffffff);  // white (diode)
                 case DeviceType::transformer: return juce::Colour (0xff2ec4b6);   // teal (transformer)
                 case DeviceType::tape: return juce::Colour (0xffa77bff);   // violet (tape)
                 case DeviceType::none: default: break; }   // explicit: keeps -Wswitch-enum consumers clean
    return juce::Colours::transparentBlack;
}

// Draw a spec as a STATIC row (no glow) — used in combo popup items. Each glyph is stroked in its
// own family colour, so a hybrid reads as a warm tube next to a blue transistor.
inline void drawDeviceSpecStatic (juce::Graphics& g, juce::Rectangle<float> area, const DeviceSpec& spec)
{
    const int total = deviceSpecCount (spec);
    if (total <= 0)
        return;
    const float cell = juce::jmin (area.getHeight(), area.getWidth() / (float) total);
    auto row = area.withSizeKeepingCentre (cell * (float) total, cell);
    int drawn = 0;
    for (const auto& [type, cnt] : spec)
    {
        if (glyphsForType (type, cnt) <= 0 || drawn >= total)
            continue;
        ++drawn;
        drawDeviceGlyph (g, row.removeFromLeft (cell).reduced (cell * 0.12f), type, deviceStroke (type));
    }
}

// The device glyph strip (OrbitCab shows it below the preamp combo): N schematic glyphs, each over
// a soft flickering glow tinted by device family — warm amber (tube), blue (BJT), green (FET). The
// flicker is the shared appkit::Flicker shimmer (the same kernel OrbitCab's poweramp heater tubes
// use), advanced by the owning editor's 30 Hz timer.
class DeviceStrip : public juce::Component
{
public:
    DeviceStrip() { setInterceptsMouseClicks (false, false); }

    void set (DeviceSpec s)
    {
        if (s == spec) return;
        spec = std::move (s); repaint();
    }

    // Advance the heater/glow flicker one frame + repaint (editor 30 Hz timer, only while visible).
    void tick()
    {
        if (spec.empty())
            return;
        glow.tick();
        repaint();
    }

    void paint (juce::Graphics& g) override
    {
        const int total = deviceSpecCount (spec);
        if (total <= 0)
            return;
        auto area = getLocalBounds().toFloat();
        const float cell = juce::jmin (area.getHeight(), area.getWidth() / (float) total);
        auto row = area.withSizeKeepingCentre (cell * (float) total, cell);
        int gi = 0;
        for (const auto& [type, cnt] : spec)
        {
            if (glyphsForType (type, cnt) <= 0 || gi >= total)
                continue;

            auto c = row.removeFromLeft (cell);
            const auto  ctr  = c.getCentre();
            // Bounded by the strip's own height as well as the cell: now that a part is drawn once,
            // the cell is as large as the row is tall, and a glow sized off it alone spilled past the
            // component — clipped to a flat-topped semicircle by whoever painted it.
            const float rad  = juce::jmin (cell * 0.66f, area.getHeight() * 0.5f);
            const float lvl  = glow.level (gi);   // clamped indexing, matches the spec's glyph cap
            const auto  gc   = deviceGlow (type); // per-glyph colour → hybrid glows amber + blue
            juce::ColourGradient grad (gc.withAlpha (0.60f * lvl), ctr.x, ctr.y,
                                       gc.withAlpha (0.0f),        ctr.x + rad, ctr.y, true);
            g.setGradientFill (grad);
            g.fillEllipse (juce::Rectangle<float> (rad * 2.0f, rad * 2.0f).withCentre (ctr));
            drawDeviceGlyph (g, c.reduced (cell * 0.14f), type, deviceStroke (type));
            ++gi;
        }
    }

private:
    DeviceSpec               spec;
    Flicker<kMaxDeviceGlyphs> glow;
};

} // namespace felitronics::appkit
